# Generated by Django 5.0.3 on 2024-04-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_alter_hero_unique_together_hero_hero_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='hero_id',
            field=models.IntegerField(unique=True),
        ),
    ]
