# Generated by Django 5.0.3 on 2024-04-09 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_alter_hero_secondary_lane_alter_hero_secondary_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroratings',
            options={'verbose_name_plural': 'Heroes Ratings'},
        ),
        migrations.AlterField(
            model_name='heroratings',
            name='hero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='hero.hero'),
        ),
    ]
