# Generated by Django 5.0.3 on 2024-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0009_alter_heroratings_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='hero_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
