# Generated by Django 5.0.3 on 2024-04-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hero',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hero',
            name='hero_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='hero_slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='hero',
            unique_together={('hero_name', 'hero_alias', 'hero_slug')},
        ),
    ]
