# Generated by Django 5.0.3 on 2024-04-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_alter_hero_options_alter_speciality_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='recomended_lane',
            new_name='primary_lane',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='hero_role',
            new_name='primary_role',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='hero_speciality',
            new_name='primary_speciality',
        ),
    ]
