# Generated by Django 5.0.3 on 2024-04-09 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_rename_recomended_lane_hero_primary_lane_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='secondary_lane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_lane', to='hero.lane'),
        ),
        migrations.AddField(
            model_name='hero',
            name='secondary_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_role', to='hero.role'),
        ),
        migrations.AddField(
            model_name='hero',
            name='secondary_speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_speciality', to='hero.speciality'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='primary_lane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_lane', to='hero.lane'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='primary_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_role', to='hero.role'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='primary_speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_speciality', to='hero.speciality'),
        ),
    ]
