# Generated by Django 5.0.3 on 2024-04-09 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0006_hero_secondary_lane_hero_secondary_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='secondary_lane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_lane', to='hero.lane'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='secondary_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_role', to='hero.role'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='secondary_speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_speciality', to='hero.speciality'),
        ),
    ]
